### ISSUE TITLE
False positive - Youtube hosts.txt

### ISSUE THREAD

**Issue by whoot** [CitizenXVIL/Hosts#2]
Hey,

the host 'r1---sn-4g5e6nl6.googlevideo.com' is probably a false positive.
On some youtube videos I got an error that there is no connection and adding this entry to the whitelist solved the problem for me.

Greetings

**Comment by CitizenXVIL** [comment]
Thanks for letting me know! I've removed it from the list.

Are you seeing any success using this list?

**Comment by whoot** [comment]
Actually I stopped using the list, because I had some problems with another video and I didnt want to go through the debugging process again.
